# Generated by Django 4.2.7 on 2023-11-20 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'companies', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='companydomain',
            options={'verbose_name': 'company domain', 'verbose_name_plural': 'company domains'},
        ),
    ]
