# Generated by Django 4.2.7 on 2023-11-23 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0002_image_alter_company_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotatedImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaves_annotations', models.ImageField(upload_to='annotated_images')),
                ('fruits_annotations', models.ImageField(upload_to='annotated_images')),
            ],
        ),
    ]
