# Generated by Django 4.2.7 on 2024-01-31 07:42

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0003_lot_geodata'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferencejob',
            name='image_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='inference_jobs_thumbs'),
        ),
    ]
