# Generated by Django 4.2.7 on 2024-01-31 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0004_inferencejob_image_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inferencejob',
            name='image_thumbnail',
        ),
    ]
