# Generated by Django 4.2.7 on 2024-02-03 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0005_remove_inferencejob_image_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='customuser',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inferencejob',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lot',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
