# Generated by Django 4.2.7 on 2024-02-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicapp', '0007_alter_customuser_created_on_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnnotatedImages',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AlterField(
            model_name='inferencejob',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inferencejob',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lot',
            name='geodata',
            field=models.FileField(blank=True, null=True, upload_to='geodata_lots'),
        ),
    ]
